alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: k8s-admin@example.com
        from: email-k8s-admin@alertmanager.com
        smarthost: mail.example.com:587
        auth_username: email-k8s-admin
        auth_password: xxxxxxxxx